name = "XRayLabTool"
uuid = "df3fe04d-a251-48f4-b0c1-7c37c180def4"
authors = ["Wei Chen <wchen@anl.gov> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
